### ISSUE TITLE
Process Serverless Output with Vite

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-plugin-vite#1]
I previously thought this wasn’t going to work because Vite was too big but I think for some projects it might work?

![image](https://user-images.githubusercontent.com/39355/158879775-c8f2b2a7-ce07-4b92-8a03-e4da1c37cd43.png)

Would need a combination of using rollup plugin-virtual to pass strings into rollup config
https://github.com/rollup/rollup/issues/3276#issuecomment-617377934
https://github.com/rollup/plugins/tree/master/packages/virtual

And vite’s `build.write` false option to get the rollup output back as an object
https://vitejs.dev/config/#build-write

**Comment by AleksandrHovhannisyan** [comment]
This would be wonderful! I think it _may_ also pave the way for Slinkity to be able to support Serverless, but maybe that's a separate issue (@Holben888 sorry to summon you—what do you think?).

(Use case: I want to be able to support URL sharing and server-render React components based on query params.)

**Comment by bholmesdev** [comment]
Oh ho ho, did somebody say `build.write: false`? That's how we server render components in Slinkity today! I think expanding this usage to HTML parsing could aid in serverless caching. [Here's our Vite build setup for reference](https://github.com/slinkity/slinkity/blob/45829c71a86cef57d224f18d1d18f8bd0431397a/packages/slinkity/cli/toViteSSR.js#L51).

We also wrote a [thin abstraction called `toCommonJSModule`](https://github.com/slinkity/slinkity/blob/main/packages/slinkity/cli/toViteSSR.js) to return modules in-memory depending on the environment. This uses `vite.server.ssrLoadModule` when in development, and `vite.build` with `write: false` for production. It also uses [a build helper we wrote](https://github.com/slinkity/slinkity/blob/main/packages/slinkity/cli/toBuilder.js) to efficiently batch multiple build requests for the same module. Not sure if _all_ of this will be of use, but I wanted to call them out for reference 😁

**Comment by bholmesdev** [comment]
Also, an important caveat I want to mention: Vite production builds aren't the _fastest_ around. Since they target HTML files as the entrypoint and could compile SCSS files on-the-fly as well, it's easy to creep into 1 second or more for a single page. I'm curious if certain files like `SCSS` should be processed ahead-of-time, with the caveat that you _can't_ use template strings to dynamically import scss. This wouldn't be allowed for example:

```html
<!--allowed and bundled at build time, before serverless requests-->
<link rel="stylesheet" href="/styles/staticPath.scss">

<!--not allowed!-->
<link rel="stylesheet" href="/styles/{{ params.dynamicPath }}.scss">
```

**Comment by AleksandrHovhannisyan** [comment]
> Also want to call out that Astro has 100% ruled out Vite in a serverless environment.

@bholmesdev Does this mean that the use case I described is not possible?

**Comment by bholmesdev** [comment]
@AleksandrHovhannisyan So it's not _impossible,_ just not recommended as the only option. the length of Vite builds and the size of the bundle make it a no-go for certain use cases. We definitely need a Vite-less option for serverless alongside the Vite-ful solution at least.

**Comment by KiwiKilian** [comment]
Closing, as serverless support of eleventy was dropped. If anyone is still interested or has a proposal, feel free to chime in!
