### ISSUE TITLE
Update to Vite 3.0

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-plugin-vite#10]
https://github.com/vitejs/vite/blob/v3.0.0/packages/vite/CHANGELOG.md#300-2022-07-13
https://github.com/vitejs/vite/releases/tag/v3.0.0

**Comment by zachleat** [comment]
v2.0.0-canary.1 has shipped with this

**Comment by matthiasott** [comment]
Fabulous, @zachleat! 🤗⚡️
