### ISSUE TITLE
Update to Vite 4

### ISSUE THREAD

**Issue by HummingMind** [11ty/eleventy-plugin-vite#19]
Vite 4 is out.
Please update to include v4 support.

Thank you!

**Comment by KiwiKilian** [comment]
I'm already successfully using `vite@4` via `overrides` in my `package.json`:
```json
  "overrides": {
    "@11ty/eleventy-plugin-vite": {
      "vite": "^4.0.0"
    }
  },
  ```

**Comment by zachleat** [comment]
Shipping with `eleventy-plugin-vite@4.0.0` thank you!
