### ISSUE TITLE
Throw a better error when the `output` folder in Eleventy matches Vite’s `publicDir` option

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-plugin-vite#23]
`publicDir: "public"` is a reserved Vite directory and Eleventy can’t use the same value for its output directory. We need a better error message here.

Found via @aarongoldenthal on this issue: https://github.com/11ty/eleventy-plugin-vite/issues/22#issuecomment-1407158803

Workaround is to change `viteOptions.publicDir` (via https://github.com/11ty/eleventy-plugin-vite#options) or to change Eleventy’s output directory.

**Comment by SleeplessByte** [comment]
This is not the reason #22 happens. With outputDir: `dist`, this still happens.

**Comment by KiwiKilian** [comment]
This was released with [v5.0.0-alpha.4](https://github.com/11ty/eleventy-plugin-vite/releases/tag/v5.0.0-alpha.4).
