### ISSUE TITLE
Help: Would love some help with this plugin’s maintenance

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-plugin-vite#43]
If you’re interested, please get in touch!

Responsibilities would include PR reviews and issue triage for this repository. There isn’t a lot of volume here!

If that goes well it may include `npm` package publishing permissions.

**Comment by Satoshi-Sh** [comment]
Hi Zach,

I'm always looking for open-source maintainer experience and eager to learn something new.

I'm not sure if I'm skilled enough to be so for this project, so it would be great if I could talk with you about the requirements.

**Comment by KiwiKilian** [comment]
For transparency: Zach added me as a maintainer to the repo while he manages the publishing.

**Comment by zachleat** [comment]
I think we can close this one, thank you so much for helping out!!
