### ISSUE TITLE
Rollup config is not executed

### ISSUE THREAD

**Issue by YonatanKra** [11ty/eleventy-plugin-vite#45]
I'm setting up the following rollup config:
```
  module.export = {
    "input": "./apps/docs/assets/bundled-scripts/live-sample.js",
    "output": {
      "dir": "./dist/apps/docs/assets/scripts/",
      "format": "cjs"
    },
    "plugins": [
      virtualPlugin,
      nodeResolve(),
      terser(),
    ]
  }
```
When I run rollup from command line, it generates the file as expected

When I run this inside an 11ty config like this:
```
	eleventyConfig.addPlugin(EleventyVitePlugin, {
		viteOptions: {
			build: {
				rollupOptions // the options imported from the config file
			}
		}
	});
```
Is there a reason why the rollup config won't be taken into account?

**Comment by KiwiKilian** [comment]
While your `rollupOptions` will be merged with the plugin defaults, `rollupOptions.input` will be overwritten by the plugin and set to the files outputted by eleventy: https://github.com/11ty/eleventy-plugin-vite/blob/main/EleventyVite.js#L58

What's the use case of your setup?

**Comment by KiwiKilian** [comment]
Closing until further feedback. Feel free to comment if your experiencing something similar.
