### ISSUE TITLE
Page build fails with Eleventy 3.0.0-beta

### ISSUE THREAD

**Issue by renekaesler** [11ty/eleventy-plugin-vite#47]
# Description

When using the Plugin with Eleventy v3.0.0-beta.1 the page build fails with an error:

```bash
[11ty] Encountered a Vite build error, restoring original Eleventy output to _site Error: Unexpected output path (was not in output directory _site): ./_site/posts/2020-04-12-sample-post/index.html
    at /tmp/vite/eleventy-plus-vite/node_modules/@11ty/eleventy-plugin-vite/EleventyVite.js:63:19
    at Array.map (<anonymous>)
    at EleventyVite.runBuild (/tmp/vite/eleventy-plus-vite/node_modules/@11ty/eleventy-plugin-vite/EleventyVite.js:61:10)
    at async AsyncEventEmitter.<anonymous> (/tmp/vite/eleventy-plus-vite/node_modules/@11ty/eleventy-plugin-vite/.eleventy.js:55:5)
    at async Promise.all (index 0)
    at async Eleventy.executeBuild (file:///tmp/vite/eleventy-plus-vite/node_modules/@11ty/eleventy/src/Eleventy.js:1338:4)
[11ty] Problem writing Eleventy templates:
[11ty] ENOENT: no such file or directory, lstat '/tmp/vite/eleventy-plus-vite/.11ty-vite'
[11ty] 
[11ty] Original error stack trace: Error: ENOENT: no such file or directory, lstat '/tmp/vite/eleventy-plus-vite/.11ty-vite'
[11ty] Copied 69 Wrote 8 files in 0.46 seconds (v3.0.0-beta.1)
```
# How to Reproduce

```
git clone https://github.com/matthiasott/eleventy-plus-vite.git
cd eleventy-plus-vite
npm install @11ty/eleventy@beta
npm i
npm run build
```

# How to Fix

I am aware of the `5.0.0alpha` branch, but i was not able to make the Project work with that. Instead with a small fix in the `4.0.0` code, the plugin worked as expected.

The reason for the issue  can be found on [Line62](https://github.com/11ty/eleventy-plugin-vite/blob/f3f9d3d505d802bb5984130a4f9879a7920fa6c7/EleventyVite.js#L62). The output directory passed by Eleventy 3.0.0 to the Plugin is now having `./` as prefix. To fix that, one could normalize the path with `path.relative`. The Code then would look like this:

```js
const outputPath = path.relative('', entry.outputPath);

if(!outputPath.startsWith(this.outputDir + path.sep)) {
  throw new Error(`Unexpected output path (was not in output directory ${this.outputDir}): ${outputPath}`);
}

return path.resolve(tmp, outputPath.substring(this.outputDir.length + path.sep.length));
```
**Note:** `substr` has been renamed to `substring`, as `substr` is deprecated.
Because I don't know about the new Eleventy 3.0 Plugin API behaviour, I also would make use of `path.relative` in the `constructor`:

```js
this.outputDir = path.relative('', outputDir);
```

I am not sure weather this fix could be helpful for you, or if its already uneccessary cause of the `5.0.0` branch. So I decided to leave this issue here.

**Comment by KiwiKilian** [comment]
Thanks for your report!

I've already contributed an [upgrade path for `eleventy-plus-vite`](https://github.com/matthiasott/eleventy-plus-vite/pull/16) which wasn't reviewed yet. The alpha branch (5.0.0 alpha) already has a fix to your reported problem and should be used with Eleventy v3.

Did you view the [alpha branch installation instructions](https://github.com/11ty/eleventy-plugin-vite/tree/alpha?tab=readme-ov-file#installation) or could you further elaborate, where you struggled to use the v5 alpha of this plugin?

**Comment by renekaesler** [comment]
Thanks for the quick response!

I have just dug a little deeper to find out where the problems with the alpha branch were. Eleventy encountered a Vite build error, because `@use '../../../node_modules/cssremedy/css/remedy.css'` hasn't been found.

```bash
[11ty] Encountered a Vite build error, restoring original Eleventy output to ./_site/ [vite:css] [sass] Can't find stylesheet to import.
  ╷
2 │ @use '../../../node_modules/cssremedy/css/remedy.css';
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/.11ty-vite/assets/css/main.scss 2:1  root stylesheet
file: /tmp/eleventy-plus-vite/src/.11ty-vite/assets/css/main.scss
```
Changing the import to `@use 'node_modules/cssremedy/css/remedy.css';` fixes the problem for the [eleventy-plus-vite](https://github.com/matthiasott/eleventy-plus-vite) project. Maybe I should make a small pull request in this project there 😄 

...But somehow that's strange for me, cause this error doesn't occur with the manually fixed  4.0.0 branch. I have no idea where this exactly comes from. It seems the path depth of the immediate files (`.11ty-vite`) differs.

**Comment by KiwiKilian** [comment]
Yes path depth differs, but this should be reverted with the next prerelease of this plugin. A non relative import was merged to the template. I guess this issue can be closed?

**Comment by renekaesler** [comment]
Yes, the issue can be closed :)
