### ISSUE TITLE
ctrl + c does not stop process when using eleventy-vite

### ISSUE THREAD

**Issue by aloxe** [11ty/eleventy-plugin-vite#49]
### Operating system

Linux Mint 21.3 Virginia

### Eleventy

3.0.0-beta.1

### Describe the bug

when running eleventy with these two packages/versions
"@11ty/eleventy": "^3.0.0-beta.1",
"@11ty/eleventy-plugin-vite": "^5.0.0-alpha.1",

it is not possible to stop the process with Ctrl-c.

The problem [was reported](https://github.com/matthiasott/eleventy-plus-vite/issues/17) on a starter that uses eleventy-plugin-vite

It is still possible to kill the process with ctrl-\

### Reproduction steps

install the latest [eleventy-plus-vite](https://github.com/matthiasott/eleventy-plus-vite) 
`npm install`
`npx @11ty/eleventy --serve`
try to close the process with `ctrl-c`

### Expected behavior

servers is stoped and you get back to the terminal  invite

**Comment by zachleat** [comment]
Just to be clear—this doesn’t happen when Vite is not in play, correct?

**Comment by KiwiKilian** [comment]
<kbd>Ctrl</kbd> + <kbd>c</kbd> does nothing, console doesn't show any change? Dev server is still reachable in browser?

**Comment by davehulse** [comment]
@KiwiKilian - to answer your question I am experiencing this using an M1 Mac on Sonoma 14.6.1 and Node v20.16.0.

**Comment by hrxkr** [comment]
> Just to be clear—this doesn’t happen when Vite is not in play, correct?

Hey @zachleat You're right! Only with Vite.
No issues even when ESbuild (v0.23.1) is used with 3.0.0-beta.1

**Comment by KiwiKilian** [comment]
I've managed to narrow down, testing with `@11ty/eleventy-plugin-vite@5.0.0-alpha.4`:

- `@11ty/eleventy <=3.0.0-alpha.17`: Works ✅
- `@11ty/eleventy >=3.0.0-alpha.18`: Broken ❌

So we need to dig into these changes @zachleat https://github.com/11ty/eleventy/compare/v3.0.0-alpha.17...v3.0.0-alpha.18

**Comment by KiwiKilian** [comment]
I've nailed it down to this commit https://github.com/11ty/eleventy/commit/2b3f18b094d0ccce88f605f7e5033d32f1f2da9d. I will handle the server close within the plugin.

**Comment by KiwiKilian** [comment]
Released as [v5.0.0-alpha.5](https://github.com/11ty/eleventy-plugin-vite/releases/tag/v5.0.0-alpha.5), let me now if you are still experiencing a problem.

**Comment by aloxe** [comment]
bumped to alpha.5 and tested ✅
