### ISSUE TITLE
does this handle external requests? like over network

### ISSUE THREAD

**Issue by wommy** [11ty/eleventy-plugin-vite#6]
because i cant get it to work, had to revert to browser-sync

**Comment by simplerethink** [comment]
@wommy do you mean using local IP?

I was able to get this working using `showAllHosts: true`

https://www.11ty.dev/docs/watch-serve/#eleventy-dev-server

**Comment by wommy** [comment]
i must have been half asleep when i wrote that

i meant to ask if the live-reload works over lan?

because of your link, i toggled `domdiff` and i still couldnt get live-reload to work over lan,

i think im going to try to ask in 11ty

**Comment by zachleat** [comment]
Duplicate of https://github.com/11ty/eleventy-dev-server/issues/20

Thanks y’all!
