### ISSUE TITLE
Starter theme?

### ISSUE THREAD

**Issue by teamcrisis** [11ty/eleventy-plugin-vite#7]
Does anyone have a starter theme using this plugin?

I have Vite generating a hashed css/SCSS file, but I can't seem to get the same working for javascript.

Any demos available?

**Comment by zachleat** [comment]
https://eleventyplusvite.netlify.app/ might be interesting to you!

https://matthiasott.com/notes/eleventy-plus-vite

**Comment by zachleat** [comment]
A couple of `Vite` results on https://www.11ty.dev/docs/starter/ too!

**Comment by tombreit** [comment]
Dear @teamcrisis , 
I've set up a (very very) minimal eleventy+eleventy-plugin-vite project with scss processing and js bundling: 
https://github.com/tombreit/eleventy-vite-minimal
